# Generated by Django 4.1.7 on 2023-04-07 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_gold_alter_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='gold1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('texts', models.TextField(blank=True)),
            ],
        ),
    ]
